import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";

import {ThemeProvider as NextThemesProvider} from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
      <html lang="en">
        <body> 
          <NextThemesProvider attribute="class" defaultTheme="dark">
            {children}
            <Navbar />
          </NextThemesProvider>
        </body>
      </html>
  );
}
